# Generated by Django 5.0 on 2024-09-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
    ]
